version: '3'
services:
  redis-server:
    image: 'redis'
  docker-test-service:
    image: aa061872/docker-test-service:latest
    restart: always
    build:
      context: ..
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "1"
  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
